Only watch files esbuild is configured to build
marvinhagemeister/karma-esbuild pull request #41
Opened 2022-01-17 21:23 UTC by theinterned

## What am I trying to accomplish?

This PR adjusts the paths watched via `chokidar` so that `karma-esbuild` only watches paths that are actually configured to be preprocessed by `esbuild`. 

Previously, `chokidar` was watching the entire base path. This can be very slow on very large projects, and it may be desirable to avoid watching certain files or directories for whatever reason (in my case certain directories were causing errors).

## What approach did I take?

It would seem the solution would be to constrain what files this watcher is set to watch. I think it would make sense to have it only watch `Object.keys(karmaConfig.preprocessors)` so it would only watch the files that `esbuild` is set to process. To be more precise, I filter `karmaConfig.preprocessors` to include only entries with "esbuild" as the preprocessor.

2022-01-17 23:56 UTC, jridgewell approved these changes

2022-01-18 00:00 UTC, jridgewell requested changes
Actually, this will constrain the watcher to only triggering on the root files, and not the dependencies that get bundled with the root file. I think we get the list of files from the `Bundle` so that we can individually register every file that gets processed by esbuild.

2022-01-18 00:13 UTC, theinterned commented
Hi, @jridgewell when you say "only triggering on the root files, and not the dependencies", by dependencies, do you mean `node_modules`? Or do you mean something else?

I'm happy to make changes so that we can get the watcher to be more selective in what it watches on. I wonder if you could suggest another direction?

Thanks!

2022-01-18 00:16 UTC, theinterned commented
FWIW, my karma config looks something like:

```js
module.exports = config => {
  config.set({
    basePath: '../',    // this is the project root
    singleRun: false,
    files: [
      'test/js/test-bootstrap.js',
      'test/unit/test-environment.js',
      'test/unit/**/test-*.js',
      'test/unit/**/test-*.ts'
    ],
    preprocessors: {
      'test/**/*.js': ['esbuild'],
      'test/**/*.ts': ['esbuild'],
      'app/**/*.ts': ['esbuild']
    },
    plugins: ['karma-*', JankyReporter]
  })
}
```

2022-01-18 01:09 UTC, jridgewell commented
Imagine you have the following, with your same `preprocessors`:

```js
// test/unit/test-foo.js
import { num } from '../../src/foo.js';

it('reloads', () => {
  console.log(num());
});


// src/foo.js
export const num = 42;
```

Editing `src/foo.js` should cause the tests to reload. But because you're only listening to changes in `test/unit/test-foo.js`, it doesn't detect the change in the dependency.

- - -

esbuild has something called a [MetaFile](https://esbuild.github.io/api/#metafile), which includes a list of all files that were bundled into the output file. We could have esbuild generate it, and add each output file to our watcher.

2022-01-18 16:05 UTC, theinterned commented
Got it! Thanks for the guidance. I'll see what I can do.

I _am_ building my source folder (`app/**/*.ts` in the config above), so this didn't initially occur to me, but I can see how other setups might not.

2022-01-18 17:39 UTC, theinterned commented
@jridgewell another approach that I think could satisfy my needs as well, would be to respect the [karma config's `excludes`](http://karma-runner.github.io/6.3/config/configuration-file.html#exclude) and use that  to exclude files from `basePath`. 

I _think_ this approach would be simpler then the MeataFile approach, while still allowing me to exclude problematic directories. Do you see any problems with this approach?

2022-02-15 20:09 UTC, theinterned commented
I'm going to close this as https://github.com/marvinhagemeister/karma-esbuild/pull/42 is a working resolution to this problem.

2022-02-15 20:09 UTC, closed without merging