Fix relative files not mapped in error output
marvinhagemeister/karma-esbuild pull request #50
Opened 2022-03-09 21:50 UTC by marvinhagemeister

This error seems to only occur when `singleBundle: false` is set in the config. When that happens the location in stack traces are often relative and not always absolute like they are with `singleBundle: true`. Our source map resolver didn't take that into account and would parse paths incorrectly (`foo/bar.js` -> `/bar.js` instead of `/foo/bar.js`). 

To resolve that the regex needed to be updated to be able to deal with relative paths and we need to construct the absolute path to get the correct object out of the bundler map.

2022-03-09 23:12 UTC, jridgewell requested changes

2022-03-09 23:12 UTC, jridgewell commented on test/fixtures/sourcemap-base-bundle/karma.conf.js
> +const envPlugin = {
I think all of this is unnecesary?

2022-03-09 23:12 UTC, jridgewell commented on src/format-error.ts
> +	const regex = /((?:\b[A-Z]:|[^ #?:(]+)?\/[^ #?:]+)[^ :]*:(\d+):(\d+)/gi;
I think this is just preventing the opening `(` from being captured as part of the URL? If so, that could just modify the existing regex:

```suggestion
	const regex = /((?:\b[A-Z]:)?[^ #?:(]+)[^ :]*:(\d+):(\d+)/gi;
```

2022-03-09 23:36 UTC, marvinhagemeister commented on test/fixtures/sourcemap-base-bundle/files/main-a.js
> +describe("simple", () => {
Great idea! I've added such a test 👍

2022-03-09 23:51 UTC, marvinhagemeister commented
Looks like the CI container has network problems right now.

2022-03-10 01:36 UTC, jridgewell approved these changes

2022-03-10 06:44 UTC, merged